In [5]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [6]:
from dotenv import load_dotenv
import os
from sqlalchemy import create_engine

load_dotenv()

engine = create_engine(
    f"postgresql://{os.getenv('DB_USER')}:{os.getenv('DB_PASS')}@"
    f"{os.getenv('DB_HOST')}:{os.getenv('DB_PORT', '5432')}/{os.getenv('DB_NAME')}"
)

In [7]:
user_anon_data = pd.read_sql("SELECT * FROM donorsearch.user_anon_data", engine)
donation_anon = pd.read_sql("SELECT * FROM donorsearch.donation_anon", engine)
donation_plan = pd.read_sql("SELECT * FROM donorsearch.donation_plan", engine)
user_anon_bonus = pd.read_sql("SELECT * FROM donorsearch.user_anon_bonus", engine)
user_donation = pd.read_sql("SELECT * FROM donorsearch.user_donation", engine)
events = pd.read_sql("SELECT * FROM donorsearch.events", engine)
bs_data = pd.read_sql("SELECT * FROM donorsearch.bs_data", engine)

In [28]:
user_anon_data['region'] = user_anon_data['region'].fillna("Не указан")

In [29]:
user_anon_data.head()

,id,gender,birth_date,region,blood_type,kell-factor,whole_blood,plasma,platelets,red_cells,...,autho_vk,autho_ok,autho_tg,autho_yandex,autho_google,confirmed_donations,icon_20,icon_100,donations_of_time_registration,count_bonuses_taken
0,276179,None,None,Не указан,None,None,True,True,True,True,...,False,False,False,False,False,0,False,False,NaN,0
1,276178,Женский,1991-05-01,"Россия, Вологодская область, Вологда",A(II) Rh+,None,True,True,True,True,...,False,False,False,False,False,0,False,False,1.0,0
2,276177,None,None,Не указан,None,None,True,True,True,True,...,False,False,False,False,False,0,False,False,NaN,0
3,276176,None,None,Не указан,None,None,True,True,True,True,...,False,False,False,False,False,0,False,False,1.0,0
4,276175,Мужской,1986-01-10,"Россия, Камчатский край, Петропавловск-Камчатский",A(II) Rh-,None,True,True,True,True,...,False,False,False,False,False,0,False,False,4.0,0

In [33]:
region = user_anon_data.groupby('region').size().reset_index(name='count').sort_values(by="count", ascending=False)
region['percentage'] = ((region['count'] / region['count'].sum()) * 100).round(1)
region.index = range(1, len(region)+1) 
region.head(10)

                                        region   count  percentage
1                                    Не указан  100574        37.8
2                               Россия, Москва   37819        14.2
3                      Россия, Санкт-Петербург   13137         4.9
4                    Россия, Татарстан, Казань    6610         2.5
5              Украина, Киевская область, Киев    3541         1.3
6   Россия, Новосибирская область, Новосибирск    3310         1.2
7   Россия, Свердловская область, Екатеринбург    3082         1.2
8                    Россия, Башкортостан, Уфа    3014         1.1
9        Россия, Красноярский край, Красноярск    2346         0.9
10       Россия, Краснодарский край, Краснодар    2186         0.8